kind = "api"
previewPath = "/api"
title = "Groove Discord Bot"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "sleep infinity"

[services.production]

[services.production.run]
args = ["node", "--no-warnings", "Shard.js"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api"

[services.production.deployConfig]
deploymentTarget = "vm"
